version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo:3.6.8
    ports:
      - "27017:27017"
    #volumes:
    # - ./docker/mongo/data:/data